name: test

on:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  ci:
    uses: jr200-labs/github-action-templates/.github/workflows/ci_npmjs.yaml@master
    with:
      node-version: '22'
      pnpm-version: '10'
      run-integration: true
